version: '3.8'
services:
  app:
    platform: linux/amd64  # Ensure this matches your environment
    build: .
    image: my-python-dev-env
    volumes:
      - .:/srv/graduation-project
    ports:
      - "7877:8777"
      - "8080:8080"
    command: uvicorn src.main:app --host 0.0.0.0 --port 8777 --reload
    container_name: graduation-project
  postgres_db:
    image: postgres:14  # 使用 PostgreSQL 14 版本的映像
    container_name: postgres-db
    environment:
      POSTGRES_USER: riceball
      POSTGRES_PASSWORD: gp12345
    ports:
      - "5430:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: riceball@gmail.com
      PGADMIN_DEFAULT_PASSWORD: gp12345
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"  # 將 MongoDB 的 27017 端口映射到主機上的 27017 端口
    volumes:
      - mongodb-data:/data/db  # 映射 MongoDB 的數據目錄到容器中的 /data/db
volumes:
  postgres-data:
  pgadmin-data:
  mongodb-data:
