version: '3.8'
services:
  app:
    platform: ${DOCKER_PLATFORM}
    build: .
    image: my-python-dev-env
    volumes:
      - .:/srv/graduation-project
    ports:
      - "7877:8777"
      - "8080:8080"
      - "8082:8082"
    command: uvicorn src.main:app --host 0.0.0.0 --port 8777 --reload
    container_name: graduation-project
    environment:
      PYTHONPATH: "/path/to/your/project_root/src:${PYTHONPATH}"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: postgres_db
      POSTGRES_PORT: 5432
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      CHANNEL_ACCESS_TOKEN: ${CHANNEL_ACCESS_TOKEN}
      CHANNEL_SECRET: ${CHANNEL_SECRET}
      MONGO_URI: ${MONGO_URI}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      MONGO_COLLECTION: ${MONGO_COLLECTION}


  postgres_db:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5430:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/var/lib/mongodb/data
    command: ["mongod", "--bind_ip_all"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=development

volumes:
  postgres-data:
  pgadmin-data:
  mongodb-data:
