version: '3.8'
services:
  app:
    platform: linux/amd64  # Ensure this matches your environment
    build: .
    image: khgt_trainning
    volumes:
      - .:/srv/KHGT
    command: python labcode_ml10m.py --data ml10m --graphSampleN 1000 --save_path model_name
    container_name: khgt_trainning