name: Check space left

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Check

      - name: Check log file sizes
        run: du -sh /home/runner/runners/2.317.0/_diag/*

      - name: Check disk space usage
        run: df -h

      - name: Check
        run: df -h /var/lib
