name: Python Application Testing

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Set environment variables
      run: |
        # (Your environment variable settings here)

    - name: Disk Space Before Docker Operations
      run: df -h

    - name: Build and run with docker-compose
      run: docker compose up -d

    - name: Install dependencies
      run: pip install -e .

    - name: Create client.json
      env:
        CLIENT_SECRETS_JSON: ${{ secrets.CLIENT_SECRETS_JSON }}
      run: |
        echo "${CLIENT_SECRETS_JSON}" > src/services/google_oidc/client.json

    - name: Verify client.json
      run: |
        ls -alh src/services/google_oidc/
        cat src/services/google_oidc/client.json

    - name: Run and test
      run: |
        docker compose exec -T app pytest

    - name: Cleanup
      run: docker compose down
      if: always()

    - name: Docker Prune
      run: docker system prune -af
      if: always()

    - name: Disk Space After Cleanup
      run: df -h
      if: always()
